name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 Git 기록을 가져와서 diff 가능하게 함

      - name: Get changed files with status
        id: changes
        run: |
          git diff --name-status HEAD~1 HEAD > changes.txt
          type changes.txt

      - name: Apply changes to deployment directory
        run: |
          $sourceRoot = "$env:GITHUB_WORKSPACE"
          $targetRoot = "C:\study\runner\ReactStudy2"

          $changes = Get-Content changes.txt

          foreach ($line in $changes) {
            $parts = $line -split "`t"
            $status = $parts[0]
            $relativePath = $parts[1]

            $sourceFile = Join-Path $sourceRoot $relativePath
            $targetFile = Join-Path $targetRoot $relativePath

            if ($status -eq "D") {
              if (Test-Path $targetFile) {
                Write-Host "Deleting $targetFile"
                Remove-Item -Path $targetFile -Force
              }
            }
            elseif ($status -eq "A" -or $status -eq "M") {
              $targetDir = Split-Path $targetFile
              if (!(Test-Path $targetDir)) {
                New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
              }
              Write-Host "Copying $sourceFile -> $targetFile"
              Copy-Item -Path $sourceFile -Destination $targetFile -Force
            }
          }